version: '3'
services:
  bar-desktop-full:
    image: johnny555/bar:v3
    #build: .
    user: ubuntu
    volumes:
      - ../:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl

    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER

    ports:
      - 5000:5000

    command: /bin/sh -c "while sleep 1000; do :; done"
