name: Build Test

on: push

jobs:
  jazzy_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@0.7.7
        with:
          required-ros-distributions: jazzy

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ros-jazzy-launch-param-builder \
            python3-rosdep
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Configure Environment
        run: |
          echo "GZ_SIM_RESOURCE_PATH=/opt/ros/jazzy/share/" >> $GITHUB_ENV
          echo "SDF_PATH=/opt/ros/jazzy/share/" >> $GITHUB_ENV

      - uses: ros-tooling/action-ros-ci@0.3.15
        with:
          target-ros2-distro: jazzy
          package-name: krytn
          colcon-defaults: |
            {
              "build": {
                "cmake-args": ["-DBUILD_TESTING=ON"],
                "symlink-install": true,
                "merge-install": true
              }
            }
