name: ROS2 Tests

on:
  push:
  pull_request:
    branches: [jazzy]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@0.7.7
        with:
          required-ros-distributions: jazzy

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ros-jazzy-launch-param-builder 
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Configure Environment
        run: |
          echo "GZ_SIM_RESOURCE_PATH=/opt/ros/jazzy/share/:/home/runner/work/bar_ws/bar_ws/ros_ws/install/share/" >> $GITHUB_ENV
          echo "SDF_PATH=/opt/ros/jazzy/share/:/home/runner/work/bar_ws/bar_ws/ros_ws/install/share/" >> $GITHUB_ENV

      - uses: ros-tooling/action-ros-ci@0.3.15
        with:
          target-ros2-distro: jazzy
          package-name: krytn
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "build": {
                "cmake-args": ["-DBUILD_TESTING=ON"],
                "symlink-install": true,
                "merge-install": true
              },
              "test": {
                "packages-select": ["krytn"],
                "event-handlers": ["console_cohesion+"],
                "merge-install": true
              }
            }
